---
AWSTemplateFormatVersion: "2010-09-09"
Description: 'Domain API Mapping'
Parameters:
  Name:
    Type: 'String'
  DomainName:
    Type: 'String'
  HostedZoneId:
    Type: 'AWS::Route53::HostedZone::Id'
Resources:
  APIGatewayDomainNameCertificate:
    Type: 'AWS::CertificateManager::Certificate'
    Properties:
      DomainName: !Ref 'DomainName'
      Tags:
        - Key: 'Name'
          Value: !Ref 'DomainName'
  APIGatewayDomainName:
    DependsOn: 'APIGatewayDomainNameCertificate'
    Type: "AWS::ApiGateway::DomainName"
    Properties: 
      CertificateArn: !Ref 'APIGatewayDomainNameCertificate'
      DomainName: !Ref 'DomainName'
  APIGatewayDomainNameRecordSetAlias:
    DependsOn: 'APIGatewayDomainName'
    Type: 'AWS::Route53::RecordSet'
    Properties:
      HostedZoneId: !Ref 'HostedZoneId'
      Name: !Ref 'DomainName'
      Type: 'A'
      AliasTarget:
        DNSName: !GetAtt 'APIGatewayDomainName.DistributionDomainName'
        HostedZoneId: 'Z2FDTNDATAQYW2'
